
id = "TotalXP"
name = "Total XP"
description = "View the total amount of XP you have!"
version = "1.0.0"
homepage = "https://github.com/yeeterlol/TotalXP"
author = "yeeter"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./TotalXP/TotalXP.csproj"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"
